services:

  ckpool:
    image: ghcr.io/getumbrel/docker-ckpool-solo:latest
    container_name: solostrike_ckpool
    restart: on-failure
    command: ["--btcsolo", "--config", "/etc/ckpool/ckpool.conf"]
    volumes:
      - ${APP_DATA_DIR}/ckpool/config:/etc/ckpool
      - ${APP_DATA_DIR}/ckpool/logs:/var/log/ckpool

  api:
    image: ghcr.io/danhaus93-ops/solostrike-api:latest
    container_name: solostrike_api
    restart: on-failure
    depends_on:
      - ckpool
    volumes:
      - ${APP_DATA_DIR}/ckpool/logs:/var/log/ckpool:ro
      - ${APP_DATA_DIR}/ckpool/config:/etc/ckpool
      - ${APP_DATA_DIR}/config:/app/config
    environment:
      - NODE_ENV=production
      - CKPOOL_LOG_DIR=/var/log/ckpool
      - CKPOOL_CONFIG_DIR=/etc/ckpool
      - CONFIG_DIR=/app/config
      - BITCOIN_RPC_HOST=${APP_BITCOIN_NODE_IP}
      - BITCOIN_RPC_PORT=${APP_BITCOIN_RPC_PORT}
      - BITCOIN_RPC_USER=${APP_BITCOIN_RPC_USER}
      - BITCOIN_RPC_PASS=${APP_BITCOIN_RPC_PASS}

  ui:
    image: ghcr.io/danhaus93-ops/solostrike-ui:latest
    container_name: solostrike_ui
    restart: on-failure
    depends_on:
      - api
    ports:
      - "${APP_PORT}:80"
